name: observ
description: "An event-oriented package. Rely on events to ensure app reactivity while triggering long calls in the background."
version: 0.1.0
# homepage: 'https://wattshout.com'
repository: 'https://github.com/wattshout/flutter-packages/tree/main/packages/observ'

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  statham: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
  
flutter: